name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check CURRENCY_SERVICE_API_KEY secret
        run: |
          if [ -z "${{ secrets.CURRENCY_SERVICE_API_KEY }}" ]; then
            echo "CURRENCY_SERVICE_API_KEY secret is not set or empty. Workflow will be halted."
            exit 1
          fi

      - name: Set Environment Variable
        run: |
          echo "export const environment = {" > src/environments/environment.ts
          echo "  production: true," >> src/environments/environment.ts
          echo "  currencyServiceApiKey: '${{ secrets.CURRENCY_SERVICE_API_KEY }}'" >> src/environments/environment.ts
          echo "};" >> src/environments/environment.ts

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/angular-currency-converter
          
